#consultas.py
QUERY_RESULTADOS = """SELECT DISTINCT
                    m.IDMETODO as idmetodo,
                    VS.NMVS + 
                    CASE 
                        WHEN vsa.cdvs = 6371 AND vsa.limitequant LIKE '0,01%' AND a.cdmatriz NOT IN (49) THEN '*'
                        WHEN COALESCE(IA.CDVS,IAA.CDVS) IS NULL THEN '*'
                        WHEN IA.CDVS IS NULL AND IAA.CDVS IS NOT NULL AND LB.CDLOCAL <> 0 THEN '**'
                        WHEN COALESCE(IA.CDVS,IAA.CDVS) IS NOT NULL AND LB.CDLOCAL = 0  THEN '**'
                        ELSE '' 
                    END AS parametro,
                    VSA.UNIDADE AS unidade,
                    VSA.VLVS  AS resultado,
                    VSA.LIMITEQUANT  as lq,
                    VSA.INFO01 as dil,
                    CASE 
                        WHEN (VSA.INCERTEZA IS NULL OR VSA.INCERTEZA = '0' OR VSA.INCERTEZA = '---') THEN '' 
                        ELSE '+-'+ VSA.INCERTEZA 
                    END AS incerteza,
                    REPLACE(VSL.TEXTO01,'<','&#60;') AS vp1,
                    REPLACE(VSL.TEXTO02,'<','&#60;') AS vp2,
                    REPLACE(VSL.TEXTO03,'<','&#60;') AS vp3,
                    dbo.datapreparo(A.CDAMOSTRA,VSA.CDMETODO) AS datapreparo,
                    dbo.clink_dataanalise_per(A.CDAMOSTRA,VSA.CDMETODO) AS dataanalise,
                    ca.CDCORRIDA AS corrida,
                    CAST(CA.NRCONTROLE1 AS VARCHAR)+'/'+CAST(CA.NRCONTROLE2 AS VARCHAR) AS nrcorrida,
                    M.DESCMETODO as metodo,
                    COALESCE(MR.NMMETODOLOGIAREFERENCIA,UD3.NMUDMETODO03) AS referencia,
                    M.IDAUXMETODO AS ref,
                    VSM.CDTIPOVSMETODO as tipovs,
                    VSA.INFO02 AS faixa,
                    CASE WHEN GVS.CDGRPVS = 0 THEN 'Parâmetros Analíticos' ELSE GVS.DESCGRPVS END as grupovs,
                    VSA.ORDEM AS ordem,
                    CASE WHEN (LB.CDLOCAL = 0) THEN 1 ELSE 0 END AS  subcontratado,
                    CASE WHEN vsa.CDPARECERVS IN (0,1) THEN 0 ELSE 1 END as parecervs,
                    CASE  
                        WHEN vsa.cdvs = 6371 AND vsa.limitequant LIKE '0,01%' AND a.cdmatriz NOT IN (49) THEN 'S'
                        WHEN (COALESCE(IA.CDVS,IAA.CDVS) IS NOT NULL AND COALESCE(AC.CDUNIDADE,ACC.CDUNIDADE) IS NOT NULL)  THEN 'S' 
                        ELSE 'N' 
                    END AS acreditado,
                    CASE 
                        WHEN (COALESCE(IA.CDVS,IAA.CDVS) IS NOT NULL AND COALESCE(AC.CDUNIDADE,ACC.CDUNIDADE) IS NOT NULL) THEN COALESCE(AC.NMACREDITACAO,ACC.NMACREDITACAO,'---') 
                        ELSE '---' 
                    END as crl,
                    REPLACE(VSA.INFO10,'<','&#60;') as info10,
                    GVS.CDGRPVS,
                    VSA.ORDEM, /* Consider removing one VSA.ORDEM if it's a duplicate column name intention */
                    VSG.ORDEM, /* This ORDEM might conflict with VSA.ORDEM if not aliased in consuming code */
                    VSA.LIMITEDET  as ld,
                    REPLACE(REPLACE(VSL.OBSVSLIMITE,'<','&#60;'),'>','&#62;') AS obsvsl,
                    dbo.der(vsa.cdamostra,vsa.cdvs) as der,
                    VEA.VLVE AS 'laudosub',
                    CASE  
                        WHEN LB.CDLABORATORIO IN (2,3,4,5,6,7,8,9,10,11,12,13,19,20) THEN 'CEIMIC NTO'
                        WHEN LB.CDLABORATORIO IN (14,15,16,17,18) THEN 'CEIMIC SUL'
                        WHEN LB.CDLOCAL = 0  THEN lb.nmlaboratorio
                    END as 'labsub',
                    LB.CDUNIDADE as cdunidade,
                    ER.analytic_method as ref2,
                    VSA.INFO08 + CASE WHEN LEN(VSA.INFO08) = 10 THEN ' 00:00:00' ELSE '' END  AS sample_ini,
                    VSA.INFO09 + CASE WHEN LEN(VSA.INFO09) = 10 THEN ' 00:00:00' ELSE '' END AS sample_end,
                    CASE WHEN campo.idauxmetodo IS NOT NULL THEN 1 ELSE 0 END as mccc,
                    vsa.info10 as trazas,
                    em.ingles as ingles,
                    A.CDAMOSTRA
                FROM 
                    AMOSTRA A
                    INNER JOIN TIPOAMOSTRA T ON T.CDTIPOAMOSTRA = A.CDTIPOAMOSTRA
                    INNER JOIN VSAMOSTRA VSA ON VSA.CDAMOSTRA = A.CDAMOSTRA
                    INNER JOIN VARSAIDA VS ON VS.CDVS = VSA.CDVS
                    INNER JOIN METODOSAM MA ON MA.CDAMOSTRA = VSA.CDAMOSTRA AND VSA.CDMETODO = MA.CDMETODO
                    INNER JOIN HISTSITMETODOSAM HM ON HM.CDAMOSTRA = A.CDAMOSTRA AND HM.CDMETODO = MA.CDMETODO AND HM.CDSITMETODO = 5
                    LEFT JOIN CORRIDAANALITICA CA ON CA.CDCORRIDA = MA.CDCORRIDA AND CA.CDCORRIDA <> 0
                    INNER JOIN METODOANALISE M ON M.CDMETODO = VSA.CDMETODO
                    INNER JOIN LIMITE L ON L.CDLIMITE = A.CDLIMITE
                    LEFT JOIN VSLIMITE VSL ON VSL.CDLIMITE = L.CDLIMITE AND VSL.CDVS = VSA.CDVS
                    LEFT JOIN UDMETODO03 UD3 ON UD3.CDUDMETODO03 = M.CDUDMETODO03
                    INNER JOIN VSMETODO VSM ON VSM.CDMETODO = VSA.CDMETODO AND VSM.CDVS = VSA.CDVS 
                    LEFT JOIN GRPVS GVS ON GVS.CDGRPVS = VSA.CDGRPVS
                    LEFT JOIN VSGRPVS  VSG ON VSG.CDGRPVS = GVS.CDGRPVS AND VSG.CDVS = VSA.CDVS
                    LEFT JOIN LABORATORIO LB ON LB.CDLABORATORIO = MA.CDLABORATORIO 
                    LEFT JOIN ACREDITACAO AC ON AC.IDAUXACREDITACAO = CASE 
                        WHEN A.CDUNIDADE IN (101) THEN 61
                        WHEN A.CDUNIDADENEG IN (90,101,102,103,104,105,106) THEN 59
                        WHEN A.CDUNIDADENEG IN (77,78) THEN 46 
                        WHEN A.CDUNIDADENEG IN (81,85) THEN 51 
                        WHEN A.CDUNIDADENEG IN (89,97) THEN 51 
                        ELSE 43 
                    END AND AC.FLATIVO = 'S'
                    LEFT JOIN ITENSACREDITACAO ia ON 
                        AC.CDACREDITACAO = IA.CDACREDITACAO
                        AND IA.IDAUXMETODO = M.IDAUXMETODO AND IA.CDVS = VSA.CDVS
                        AND (IA.IDAUXTIPOAMOSTRA = T.IDAUXTIPOAMOSTRA OR IA.CDMATRIZ = A.CDMATRIZ)
                    LEFT JOIN ACREDITACAO ACC ON ACC.CDUNIDADE = LB.CDUNIDADE 
                        AND ACC.FLATIVO = 'S' AND ACC.IDAUXACREDITACAO NOT IN (AC.IDAUXACREDITACAO) 
                    LEFT JOIN ITENSACREDITACAO IAA ON 
                        ACC.CDACREDITACAO = IAA.CDACREDITACAO 
                        AND IAA.IDAUXMETODO = M.IDAUXMETODO AND IAA.CDVS = VSA.CDVS
                        AND (IAA.IDAUXTIPOAMOSTRA = T.IDAUXTIPOAMOSTRA OR IAA.CDMATRIZ = A.CDMATRIZ)
                    LEFT JOIN ESCOPOANALITICO EA ON EA.CDUNIDADE = LB.CDUNIDADE
                    LEFT JOIN VSESCOPOANALITICO VSE ON VSE.CDESCOPOANALITICO = EA.CDESCOPOANALITICO 
                        AND VSE.CDVS = VSA.CDVS AND VSE.IDAUXMETODO = M.IDAUXMETODO AND VSE.IDAUXTIPOAMOSTRA = T.IDAUXTIPOAMOSTRA
                    LEFT JOIN VSESCOPOANALITICO VSEM ON VSEM.CDESCOPOANALITICO = EA.CDESCOPOANALITICO 
                        AND VSEM.IDAUXMETODO = M.IDAUXMETODO AND VSEM.CDVS = VSA.CDVS AND VSEM.CDMATRIZ = A.CDMATRIZ AND VSEM.IDAUXTIPOAMOSTRA = 0 
                    LEFT JOIN METODOLOGIAREFERENCIA MR ON MR.CDMETODOLOGIAREFERENCIA = COALESCE( VSE.CDMETODOLOGIAREFERENCIA,VSEM.CDMETODOLOGIAREFERENCIA) 
                    LEFT JOIN VEMETODO VEM ON VEM.CDMETODO = VSA.CDMETODO AND VEM.CDVE = 43
                    LEFT JOIN VEAMOSTRA VEA ON VEA.CDVEMETODO = VEM.CDVEMETODO AND VEA.CDAMOSTRA = A.CDAMOSTRA 
                    LEFT JOIN onlinedata.dbo.EDD_REF ER ON ER.NMCEIMIC = COALESCE(MR.NMMETODOLOGIAREFERENCIA,UD3.NMUDMETODO03) 
                        AND ER.IDEDD = CASE 
                            WHEN A.CDUNIDADE IN (101) THEN 9980
                            WHEN A.CDUNIDADENEG IN (90,101,102,103,104,105,106) THEN 9990 
                            ELSE 9999 
                        END
                    LEFT JOIN onlinedata.dbo.EDD_METHOD em ON em.idauxmetodo = m.idauxmetodo 
                        AND em.idedd = CASE 
                            WHEN A.CDUNIDADE IN (101) THEN 9980
                            WHEN A.CDUNIDADENEG IN (90,101,102,103,104,105,106) THEN 9990 
                            ELSE 9999 
                        END
                    LEFT JOIN onlinedata.dbo.CLINK_MET_CAMPO_PERU campo ON campo.idauxmetodo = M.idauxmetodo
                WHERE 
                    a.cdamostra = ? 
                    AND A.FLATIVO = 'S' AND a.CDCLASSEAMOSTRA = 1
                    AND vsa.flimprime = 'S' AND VSM.CDTIPOVSMETODO = 1 AND vsa.cdvs NOT IN (1701)
                    AND dbo.clink_met_hidrobiologia(m.idauxmetodo) = 0 
                    AND VSA.VLVS <> 'ND' -- Nota: Esta condición estaba comentada como específica para un cdamostra. Verifica si debe aplicar a todos.
                ORDER BY 
                    GVS.CDGRPVS, VSA.ORDEM, VSG.ORDEM; -- Añadido un ORDER BY de ejemplo, ajusta según necesites
                """

QUERY_ENCABEZADOS = """
SELECT
    A.IDAMOSTRA AS identificacao,
    CASE 
        WHEN ISNULL(dbo.infos(A.CDAMOSTRA,962),'') = '' THEN (COALESCE(CONVERT(VARCHAR,A.DTPUBLICACAO,103),CONVERT(VARCHAR,GETDATE(),103))) 
        ELSE 
            ((CASE WHEN DAY(dbo.infos(A.CDAMOSTRA,962)) < 10 THEN '0' + CAST(DAY(dbo.infos(A.CDAMOSTRA,962)) AS VARCHAR(10)) ELSE CAST(DAY(dbo.infos(A.CDAMOSTRA,962)) AS VARCHAR(10)) END) + '/' + 
            (CASE WHEN MONTH(dbo.infos(A.CDAMOSTRA,962)) < 10 THEN '0' + CAST(MONTH(dbo.infos(A.CDAMOSTRA,962)) AS VARCHAR(10)) ELSE CAST(MONTH(dbo.infos(A.CDAMOSTRA,962)) AS VARCHAR(10)) END) + '/' + 
            CAST(YEAR(dbo.infos(A.CDAMOSTRA,962)) AS VARCHAR(10)))
    END AS data_emissao,
    ES.RAZAOSOCIAL + (CASE WHEN ISNULL(ES.NMUDEMPRESA04, '') != '' THEN ' (' + ES.NMUDEMPRESA04 + ')' ELSE '' END) as solicitante,
    COALESCE(OG.OBS,OP.OBS,(
        CASE WHEN LN.NMLOGRADOURO IS NOT NULL THEN + LN.NMLOGRADOURO + ' ' ELSE '' END + 
        CASE WHEN EN.ENDERECO IS NOT NULL THEN EN.ENDERECO + ' ' ELSE '' END + 
        CASE WHEN EN.NUMERO IS NOT NULL THEN EN.NUMERO ELSE '' END +
        CASE WHEN EN.COMPLEMENTO IS NOT NULL THEN ' ' + EN.COMPLEMENTO + ' ' ELSE '' END +
        CASE WHEN EN.OBSENDERECO IS NOT NULL THEN ' ' + EN.OBSENDERECO +' - ' ELSE ' - ' END +
        CASE WHEN EN.BAIRRO IS NOT NULL THEN EN.BAIRRO + ' - ' ELSE '' END + 
        CASE WHEN CD.NMCIDADE IS NOT NULL THEN CD.NMCIDADE + ' - ' ELSE '' END + 
        CASE WHEN ISNULL(ESM.NMESTADO, '') = '' THEN (CASE WHEN ED.NMESTADO IS NOT NULL THEN ED.NMESTADO ELSE '' END) ELSE ESM.NMESTADO END 
    ))  AS endereco, 
    ES.NMUDEMPRESA01 AS eo_solicitante,
    CASE 
        WHEN ISNULL(OGP.OBS, '') = '' THEN (CASE WHEN ISNULL(OPR.OBS, '') = '' THEN P.IDPROCESSO ELSE OPR.OBS END) 
        ELSE OGP.OBS 
    END as idprocesso,
    CE.NMCONTATO + ' ' + CE.SOBRENOME AS contato,
    T.NMTIPOAMOSTRA AS matriz,
    CASE 
        WHEN A.cdmatriz IN (8) THEN LEFT(dbo.fechahora(A.DTCOLETA),10) 
        ELSE dbo.fechahora(A.DTCOLETA) 
    END AS datacoleta,
    CASE 
        WHEN ISNULL(UD.NMUDAMOSTRA09,'') != '' THEN LEFT(UD.NMUDAMOSTRA09,10) 
        ELSE LEFT(dbo.fechahora(dbo.infos(A.CDAMOSTRA,CASE WHEN A.CDUNIDADE IN (123) THEN 957 ELSE 611 END)),10) 
    END as datachegada,
    L.DESCLIMITE AS limite,
    U.NMUSUARIO AS responsavel,
    U.TITULO as cargo,
    U.CDUSUARIO as cdusuario,
    dbo.cant_limites(A.CDAMOSTRA) as cant_limites,
    dbo.infos(A.CDAMOSTRA,610) AS respcoleta,
    L.NMLIMITE01 AS limite1,
    L.NMLIMITE02 AS limite2,
    L.NMLIMITE03 AS limite3,
    CASE 
        WHEN ISNULL(UD.NMUDAMOSTRA08,'') != '' THEN NMUDAMOSTRA08 
        ELSE dbo.infos(A.CDAMOSTRA,615) 
    END as lugar_muestreo,
    CASE WHEN dbo.infos(A.CDAMOSTRA,678) IS NULL THEN 'N/A' ELSE dbo.infos(A.CDAMOSTRA,678) END  as cod_cliente,
    CASE WHEN dbo.infos(A.CDAMOSTRA,679) IS NULL THEN 'N/A' ELSE dbo.infos(A.CDAMOSTRA,679) END  as variedad,
    CASE WHEN dbo.infos(A.CDAMOSTRA,680) IS NULL THEN 'N/A' ELSE dbo.infos(A.CDAMOSTRA,680) END  as muestreador,
    CASE WHEN dbo.infos(A.CDAMOSTRA,681) IS NULL THEN 'N/A' ELSE dbo.infos(A.CDAMOSTRA,681) END  as productor,
    CASE WHEN dbo.infos(A.CDAMOSTRA,682) IS NULL THEN 'N/A' ELSE dbo.infos(A.CDAMOSTRA,682) END  as cod_productor,
    CASE WHEN dbo.infos(A.CDAMOSTRA,773) IS NULL THEN 'N/A' ELSE dbo.infos(A.CDAMOSTRA,773) END  as huerto,
    CASE WHEN dbo.infos(A.CDAMOSTRA,684) IS NULL THEN 'N/A' ELSE dbo.infos(A.CDAMOSTRA,684) END  as reg_agricola,
    CASE 
        WHEN ISNULL(dbo.infos(A.CDAMOSTRA,685),'') = '' THEN (SELECT OBS FROM OBSAMOSTRA WHERE CDAMOSTRA = A.CDAMOSTRA AND CDTIPOOBSERVACAO = 145 AND FLATIVO = 'S') 
        ELSE dbo.infos(A.CDAMOSTRA,685) 
    END  as info_adic,
    (SELECT CHAVEPUBLICACAO FROM AMOSTRA WHERE cdamostra = a.cdamostra) as checksum,
    A.CDUNIDADE AS unidade,
    UD.NMUDAMOSTRA01+'/'+UD.NMUDAMOSTRA02 AS coordenadas,
    dbo.infos(A.CDAMOSTRA,40) AS coletor,
    dbo.coleta_amostra(A.CDAMOSTRA) as coleta,
    dbo.infos(A.CDAMOSTRA,189) as nro_canister,
    CAST(A.CDAMOSTRA AS VARCHAR) +' - relatorio'  AS nome_laudo,
    dbo.clink_equipos_campo_amostra(A.CDAMOSTRA) AS equipos_coleta,
    CASE WHEN L.IDAUXLIMITE IN (170,245,284,292,302) THEN 1 ELSE 0 END as consema,
    A.SUPLEMENTO AS versao,
    CAST(A.NRCONTROLE1 AS VARCHAR)+'/'+CAST(A.NRCONTROLE2 AS VARCHAR)+'-'+CAST(A.NRCONTROLE3 AS VARCHAR)+'.' AS numero_base,
    A.CDUNIDADENEG AS unidadeneg,
    CASE 
        WHEN (ES.FLPESSOAFISICA = 'S' AND ISNULL(ES.CNPJCPF, '') = '') THEN ES.NMUDEMPRESA03 
        ELSE ES.CNPJCPF 
    END AS ruc,
    ISNULL((SELECT TOP 1 COUNT(idauxmetodo) FROM METODOANALISE WHERE cdmetodo IN (SELECT cdmetodo FROM METODOSAM WHERE cdamostra = A.CDAMOSTRA ) AND dbo.clink_met_hidrobiologia(idauxmetodo) =1 ),0) as hidros,
    CASE WHEN ISNULL(UD.NMUDAMOSTRA01,'') != '' THEN NMUDAMOSTRA01 ELSE dbo.infos(A.CDAMOSTRA,612) END as norte,
    CASE WHEN ISNULL(UD.NMUDAMOSTRA02,'') != '' THEN NMUDAMOSTRA02 ELSE dbo.infos(A.CDAMOSTRA,613) END as este,
    CASE WHEN ISNULL(UD.NMUDAMOSTRA07,'') != '' THEN NMUDAMOSTRA07 ELSE dbo.infos(A.CDAMOSTRA,614) END as zona,
    CASE 
        WHEN ISNULL(dbo.infos(A.CDAMOSTRA,961),'') = '' THEN CONVERT(VARCHAR,HF.DTSITAMOSTRA,103) 
        ELSE 
            ((CASE WHEN DAY(dbo.infos(A.CDAMOSTRA,961)) < 10 THEN '0' + CAST(DAY(dbo.infos(A.CDAMOSTRA,961)) AS VARCHAR(10)) ELSE CAST(DAY(dbo.infos(A.CDAMOSTRA,961)) AS VARCHAR(10)) END) + '/' + 
            (CASE WHEN MONTH(dbo.infos(A.CDAMOSTRA,961)) < 10 THEN '0' + CAST(MONTH(dbo.infos(A.CDAMOSTRA,961)) AS VARCHAR(10)) ELSE CAST(MONTH(dbo.infos(A.CDAMOSTRA,961)) AS VARCHAR(10)) END) + '/' + 
            CAST(YEAR(dbo.infos(A.CDAMOSTRA,961)) AS VARCHAR(10)))
    END AS datafin,
    CONVERT(VARCHAR, (
        SELECT dbo.fecha_amd(
            (CASE WHEN DAY(VEA.VLVE) < 10 THEN '0' + CAST(DAY(VEA.VLVE) AS VARCHAR(10)) ELSE CAST(DAY(VEA.VLVE) AS VARCHAR(10)) END) + '/' + 
            (CASE WHEN MONTH(VEA.VLVE) < 10 THEN '0' + CAST(MONTH(VEA.VLVE) AS VARCHAR(10)) ELSE CAST(MONTH(VEA.VLVE) AS VARCHAR(10)) END) + '/' + 
            CAST(YEAR(VEA.VLVE) AS VARCHAR(10))
        )
        FROM VEAMOSTRA VEA
        INNER JOIN VEMETODO VEM ON VEM.CDVEMETODO = VEA.CDVEMETODO
        INNER JOIN METODOSAM MA ON MA.CDAMOSTRA = VEA.CDAMOSTRA AND MA.CDMETODO = VEM.CDMETODO
        WHERE VEA.CDAMOSTRA = A.CDAMOSTRA  AND VEM.CDVE = (CASE WHEN A.CDUNIDADE IN (123) THEN 4 ELSE 234 END)
        AND VEA.DTEDICAO = (
            SELECT MAX(VEA_INNER.DTEDICAO)
            FROM VEAMOSTRA VEA_INNER
            INNER JOIN VEMETODO VEM_INNER ON VEM_INNER.CDVEMETODO = VEA_INNER.CDVEMETODO
            WHERE VEA_INNER.CDAMOSTRA = A.CDAMOSTRA AND VEM_INNER.CDVE = (CASE WHEN A.CDUNIDADE IN (123) THEN 4 ELSE 234 END)
            -- GROUP BY VEA_INNER.CDAMOSTRA, VEM_INNER.CDVE -- Group by no es necesario en subconsulta MAX escalar
        )
    ),103) AS dataini,
    CASE WHEN dbo.infos(A.CDAMOSTRA,677) IS NULL THEN 'N/A' ELSE dbo.infos(A.CDAMOSTRA,677) END  as desc_amostra,
    (SELECT descopcao FROM OPCOESINFO WHERE cdinfo = 781 AND nmopcao = dbo.infos(A.CDAMOSTRA,781)) as lng,
    CASE dbo.infos(A.CDAMOSTRA,772) 
        WHEN 'Ordenado' THEN 1
        WHEN 'Alfabético' THEN 2
        WHEN 'Detectados' THEN 3
        ELSE 0 
    END as tipo_informe_food,
    A.IDPROCESSO AS idcontrole,
    tipofirma = (
        SELECT MAX(R.CANTIDAD)
        FROM (
            SELECT ME.IDAUXMETODO, CANTIDAD = (CASE WHEN ME.IDAUXMETODO IN (2470,2833,2862) THEN 1 ELSE 0 END)
            FROM METODOSAM MAM
            LEFT JOIN METODOANALISE ME ON ME.CDMETODO = MAM.CDMETODO
            WHERE MAM.CDAMOSTRA = A.CDAMOSTRA
        ) R
    ),
    flincerteza = (
        SELECT MAX(R.CANTIDAD)
        FROM (
            SELECT ME.IDAUXMETODO, CANTIDAD = (CASE WHEN ME.IDAUXMETODO IN (2321,2322,2065,2072) THEN 1 ELSE 0 END)
            FROM METODOSAM MAM
            LEFT JOIN METODOANALISE ME ON ME.CDMETODO = MAM.CDMETODO
            WHERE MAM.CDAMOSTRA = A.CDAMOSTRA
        ) R
    ),
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,945) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,945) END AS est_senasa,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,946) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,946) END AS matriz_especie,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,947) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,947) END AS origen_mue,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,948) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,948) END AS condicion_mue,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,949) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,949) END AS identificacion_mue,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,495) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,495) END AS lote,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,950) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,950) END AS dataelaboracion,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,951) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,951) END AS datavencimiento,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,952) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,952) END AS nromue_cliente,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,953) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,953) END AS nropartida,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,528) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,528) END AS marca,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,954) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,954) END AS nroprecinto,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,955) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,955) END AS procedencia_mue,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,956) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,956) END AS destino_lote,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,957) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,957) END AS datarecepcion,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,958) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,958) END AS nroacta,
    CASE WHEN DBO.INFOS(A.CDAMOSTRA,959) IS NULL THEN '' ELSE DBO.INFOS(A.CDAMOSTRA,959) END AS nrosenasa,
	CAST(P.NRCONTROLE1 AS VARCHAR) +'/'+CAST(p.NRCONTROLE2 AS VARCHAR) as NMPROCESSO
FROM 
    AMOSTRA A
    LEFT JOIN AMOSTRASGRPAMOSTRA AGA ON AGA.CDAMOSTRA = A.CDAMOSTRA
    LEFT JOIN GRPAMOSTRA G ON G.CDGRPAMOSTRA = AGA.CDGRPAMOSTRA
    LEFT JOIN OBSGRPAMOSTRA OG ON OG.CDGRPAMOSTRA = G.CDGRPAMOSTRA AND OG.CDTIPOOBSERVACAO = 108 AND OG.FLATIVO = 'S'
    LEFT JOIN OBSGRPAMOSTRA OGP ON OGP.CDGRPAMOSTRA = G.CDGRPAMOSTRA AND OGP.CDTIPOOBSERVACAO = 146 AND OGP.FLATIVO = 'S'
    INNER JOIN TIPOAMOSTRA T ON T.CDTIPOAMOSTRA = A.CDTIPOAMOSTRA
    INNER JOIN AMOSTRASITENSPRO AIP ON AIP.CDAMOSTRA = A.CDAMOSTRA
    INNER JOIN PROCESSO P ON P.CDPROCESSO = AIP.CDPROCESSO
    LEFT JOIN OBSPROCESSO OP ON OP.CDPROCESSO = P.CDPROCESSO AND OP.CDTIPOOBSERVACAO = 108 AND OP.FLATIVO = 'S'
    LEFT JOIN OBSPROCESSO OPR ON OPR.CDPROCESSO = P.CDPROCESSO AND OPR.CDTIPOOBSERVACAO = 146 AND OPR.FLATIVO = 'S'
    INNER JOIN EMPRESA ES ON ES.CDEMPRESA = A.CDEMPRESASOL
    LEFT JOIN CONTATOSEMP CE ON CE.CDCONTATO = A.CDCONTATOSOL
    LEFT JOIN ENDERECOSEMP ENE ON ENE.CDEMPRESA = ES.CDEMPRESA AND ENE.CDTIPOENDERECO = 1
    LEFT JOIN ENDERECO EN ON EN.CDENDERECO = ENE.CDENDERECO
    LEFT JOIN LOGRADOURO LN ON LN.CDLOGRADOURO = EN.CDLOGRADOURO
    LEFT JOIN CIDADE CD ON CD.CDCIDADE = EN.CDCIDADE
    LEFT JOIN ESTADO ED ON ED.CDESTADO = EN.CDESTADO
    LEFT JOIN onlinedata.dbo.ESTADO ESM ON ESM.CDESTADO = EN.CDESTADO -- Asumiendo que onlinedata es un linked server
    LEFT JOIN ENDERECOSEMP ENC ON ENC.CDEMPRESA = ES.CDEMPRESA AND ENC.CDTIPOENDERECO = 2
    LEFT JOIN ENDERECO EC ON EC.CDENDERECO = ENC.CDENDERECO
    LEFT JOIN LOGRADOURO LC ON LC.CDLOGRADOURO = EC.CDLOGRADOURO 
    LEFT JOIN CIDADE CC ON CC.CDCIDADE = EC.CDCIDADE
    LEFT JOIN ESTADO ET ON ET.CDESTADO = EC.CDESTADO
    LEFT JOIN LIMITE L ON L.CDLIMITE = A.CDLIMITE
    LEFT JOIN HISTSITAMOSTRA H ON H.CDAMOSTRA = A.CDAMOSTRA AND H.CDSITAMOSTRA = 4
    LEFT JOIN (
        SELECT CDAMOSTRA, DTSITAMOSTRA = MAX(DTSITAMOSTRA) 
        FROM HISTSITAMOSTRA 
        WHERE CDSITAMOSTRA = 3 
        GROUP BY CDAMOSTRA
    ) HF ON HF.CDAMOSTRA = A.CDAMOSTRA
    LEFT JOIN USUARIO U ON U.CDUSUARIO = H.CDUSUARIO
    INNER JOIN UDSAMOSTRA UD ON UD.CDAMOSTRA = A.CDAMOSTRA
    INNER JOIN EMPRESA CONT ON CONT.CDEMPRESA = A.CDEMPRESACON
WHERE
    A.FLATIVO = 'S' 
    AND A.CDCLASSEAMOSTRA = 1 
    AND P.VERPROCESSO = (SELECT MAX(VERPROCESSO) FROM PROCESSO P_INNER WHERE P_INNER.IDAUXPROCESSO = P.IDAUXPROCESSO)
    AND A.CDAMOSTRA = ?;
"""